#!/usr/bin/env bash

alias cp="cp -iv"
alias mv="mv -iv"
alias md="mkdir -pv"
alias rm="rm -iv"
alias c="clear"
alias ka="killall"
alias yd="youtube-dl --add-metadata -i"
alias yda="yd -x -f bestaudio/best"
alias ls="gls -hFN --color=auto --group-directories-first" # use GNU ls
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias iftop="sudo /usr/local/sbin/iftop"

# z.lua
alias zl="z -l"
alias zc="z -c"
alias zb="z -b"
alias zi="z -i"
alias zf="z -I"

# Improved
alias idu="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
alias icat="highlight --out-format=ansi"

# Use neovim for vim if present
command -v nvim >/dev/null && alias vim="nvim" vi="nvim" v="nvim" vimdiff="nvim -d"

# Dotfiles management
alias cfg="git --git-dir=$HOME/dotfiles/ --work-tree=$HOME"

# Convert video to GIF (with 2K resolution) using ffmpeg
# Usage: vtg input_name output_name, then output_name.gif will be generated
alias vtg='function video_to_gif(){ ffmpeg -i $1 -pix_fmt rgb8 -r 10 -vf scale=2560:-1 $2.gif && gifsicle -O3 $2.gif -o $2.gif && osascript -e "display notification \"$2.gif successfully converted and saved\" with title \"VIDEO2GIF SUCCESS!\""};video_to_gif'

# Quick navigation & config
alias cdl="cd ~/Downloads"
alias cc="cd ~/.config"
alias cb="cd ~/.config/bin"
alias cg="cd ~/gitrepos"
alias cfv="$EDITOR ~/.config/nvim/init.vim"
alias cfz="$EDITOR ~/.config/zsh/.zshrc"
alias cfa="$EDITOR ~/.config/zsh/aliases"
alias cfe="$EDITOR ~/.config/zsh/env"
