#!/usr/bin/env zsh

# Use menu selection for completion
zstyle ':completion:*' menu select
zmodload zsh/complist

autoload -Uz compinit
compinit

# Include hidden files in autocomplete
_comp_options+=(globdots)

# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# For kitty kitten: hyperlinked grep (defined in ~/.config/zsh/functions/hg)
# Delegate its completion to rg
compdef _rg hg

# Completion for other programs
fpath=($HOME/.config/zsh/completions $fpath)
