#!/usr/bin/env zsh

# Remove duplicated commands in history
setopt HIST_IGNORE_ALL_DUPS

# Prompt for spelling correction of commands.
setopt CORRECT

# Make right prompt aligned to the rightmost
ZLE_RPROMPT_INDENT=0

# My own defined autoload functions (under ~/.config/zsh/functions/)
fpath+=${0:h}/functions
autoload -Uz ${0:h}/functions/*(.:t)

# Change open files limit on macOS
ulimit -n 524288
ulimit -u 2048
