#!/usr/bin/env zsh

# Remove duplicated commands in history
setopt HIST_IGNORE_ALL_DUPS

# Prompt for spelling correction of commands.
setopt CORRECT

# Make right prompt aligned to the rightmost
ZLE_RPROMPT_INDENT=0

# My own defined autoload functions (under ../functions/)
fpath+=${0:h}/functions
autoload -Uz ${0:h}/functions/*(.:t)
