#!/usr/bin/env zsh

# Using zimfw as the plugin manager

if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

# The prefix for the alias from zim builtin git module
#zstyle ':zim:git' aliases-prefix 'g'

# Append `../` to your input for each `.` you type after an initial `..`
zstyle ':zim:input' double-dot-expand yes

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# fzf-tab
# Fix https://github.com/Aloxaf/fzf-tab/issues/24
zstyle -d ':completion:*' format
zstyle ':completion:*:descriptions' format '[%d]'
# Preview
zstyle ':fzf-tab:*' fzf-flags '--preview-window=hidden,<9999(hidden)'
zstyle ':fzf-tab:*' fzf-preview 'echo Preview is not available!'
