require('nvim-treesitter.configs').setup({
    ensure_installed = {
        'bash',
        'c',
        'cpp',
        'cmake',
        'css',
        'go',
        'graphql',
        'html',
        'java',
        'javascript',
        'json',
        'jsonc',
        'json5',
        'lua',
        'make',
        'markdown',
        'markdown_inline',
        'python',
        'query', -- treesitter query
        'rust',
        'scss',
        'sql',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'vimdoc',
        'yaml',
    },
    ignore_install = {},
    highlight = {
        enable = true,
    },
    incremental_selection = {
        enable = false,
        -- keymaps = {
        --     init_selection = '<Enter>',
        --     node_incremental = '<Enter>',
        --     node_decremental = '<BS>',
        --     scope_incremental = '<S-Enter>',
        -- },
    },
})
