-- Load plugin configs
local modules = {
  'bqf',
  'cmp',
  'comment',
  'conform',
  'eregex',
  'flatten',
  'fugitive',
  'fzf',
  'gitsigns',
  'hlargs',
  'harpoon',
  'inc-rename',
  'iswap',
  'lualine',
  'luasnip',
  'lspconfig',
  'neogen',
  'nvim-colorizer',
  'nvim-navic',
  'nvim-navbuddy',
  'nvim-ts-context-commentstring',
  'project',
  'quick-scope',
  'targets',
  'treesitter',
  'treesitter-textobjects',
  'treesj',
  'telescope',
  'telescope-tabs',
  'undotree',
  'vim-asterisk',
  'vim-flog',
  'vim-grepper',
  'vim-illuminate',
}

for _, module in ipairs(modules) do
  require('rockyz.plugins.' .. module)
end
