-- Reference: https://zhuanlan.zhihu.com/p/36279445

local g = vim.g
local fn = vim.fn

-- Tips: If we need the tags for a project not managed by vcs, we can touch a .root file under the project root folder
g.gutentags_project_root = {'.git', '.root', '.project'}

-- Tag file name for ctags
g.gutentags_ctags_tagfile = '.tags'

-- Using both ctags and gtags
g.gutentags_modules = {}
if fn.executable('ctags') then  -- the ctags file generated by gutentags will be prepended to 'tags' option
  table.insert(g.gutentags_modules, 'ctags')
end
if fn.executable('gtags-cscope') and fn.executable('gtags') then
  table.insert(g.gutentags_modules, 'gtags_cscope') -- 'cscopeprg' will be set to gtags-cscope
end

-- Move tag files out of project dir to avoid being polluted
g.gutentags_cache_dir = fn.expand('~/.cache/tags')

-- Options for ctags
-- g.gutentags_ctags_extra_args = ['--fields=+niazS', '--extras=+q']

-- Disable connecting gtags database automatically (gutentags_plus will handle the database connection)
g.gutentags_auto_add_gtags_cscope = 0

-- Disable default maps
g.gutentags_plus_nomap = 1

-- Focus to quickfix window after searching
g.gutentags_plus_switch = 1
