#!/usr/bin/env sh

# ====
# Initialization
# ====

source ~/.config/yabai/scripts/initialization.sh

# ====
# Rules
# ====

yabai -m rule --add app=".* Preferences|System Information|Archive Utility|EuDic|Activity Monitor|Karabiner|App Store|Fantastical" manage=off

# ====
# Signals
# ====

# Initialize the temp folder when adding or removing displays
yabai -m signal --add event=display_added action="~/.config/yabai/scripts/initialization.sh"
yabai -m signal --add event=display_removed action="~/.config/yabai/scripts/initialization.sh"

# ====
# global settings
# ====

# General
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config insert_feedback_color        0xaad75f5f

# Window
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# Window border
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555

# Mouse
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# ====
# Space settings
# ====

yabai -m config layout                       bsp
yabai -m config top_padding                  31
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

echo "yabai configuration loaded.."
