#!/usr/bin/env sh

# ====
# Initialization
# ====

source ~/.config/yabai/scripts/initialization.sh

# ====
# Rules
# ====

yabai -m rule --add app=".* Preferences|Finder|System Information|Archive Utility|EuDic|Activity Monitor|Karabiner|App Store|Bartender|1Password .*" manage=off
yabai -m rule --add title="Preferences" manage=off
yabai -m rule --add app="Fantastical Helper" border=off manage=off # Fantastical menu bar drop-down menu
yabai -m rule --add app="kitty|Alacritty|iTerm2" border=on
yabai -m rule --add app="Installer" manage=off

# ====
# Signals
# ====

# Initialize the temp folder when adding or removing displays
yabai -m signal --add event=display_added action="~/.config/yabai/scripts/initialization.sh"
yabai -m signal --add event=display_removed action="~/.config/yabai/scripts/initialization.sh"

# ====
# Configs
# ====

# General
yabai -m config layout                       bsp
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config insert_feedback_color        0xaad75f5f

# Window
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# Window border
yabai -m config window_border off
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xff42A5F5
yabai -m config normal_window_border_color 0xff555555

# Mouse
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Paddings
yabai -m config external_bar all:26:0   # top padding for status bar (it won't be affected by --toggle padding)
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

echo "yabai configuration loaded.."
