#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             26
spacebar -m config spacing_left       25
spacebar -m config spacing_right      20
spacebar -m config text_font          "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font          "FontAwesome:Regular:12.0"
spacebar -m config background_color   0xff202020
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff14b1ab
spacebar -m config power_icon_color   0xfff69e7b
spacebar -m config battery_icon_color 0xffffbcbc
spacebar -m config dnd_icon_color     0xfffcf7bb
spacebar -m config clock_icon_color   0xff99d8d0
spacebar -m config space_icon_strip   1:\  2:\  3:\  4 5 6 7 8 9 10
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%m/%d/%y %R"

echo "spacebar configuration loaded.."
