#!/usr/bin/env zsh

# FZF builtin key bindings and completion
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh

export FD_DEFAULT_OPTS="--hidden --follow --exclude .git"

# Use fd instead of default find
export FZF_DEFAULT_COMMAND="fd $FD_DEFAULT_OPTS"

# Default options when run ZFZ
# Key bindings:
#   ctrl-v: open via EDITOR
#   ctrl-t: open via EDITOR in a separate terminal window
#   ctrl-o: open via the default application
#   ctrl-y: copy to system clipboard
#   ctrl-d: move cursor half page down
#   ctrl-u: move cursor half page up
#   ctrl-a: select all
export FZF_DEFAULT_OPTS="--preview '( \
                                        bat --color=always --style=numbers,changes,header --theme=base16 {} 2> /dev/null \
                                        || ( [[ \$(file -b {}) == directory ]] && tree -C {} || echo -e This whole line is:\"\n\n\" {} ) \
                                    ) | head -200' \
                         --preview-window :wrap \
                         --bind 'ctrl-v:execute(\$EDITOR {+} < /dev/tty > /dev/tty 2>&1),ctrl-y:execute-silent(echo -n {+} | pbcopy),ctrl-t:execute(nohup /Applications/Alacritty.app/Contents/MacOS/alacritty -e \$EDITOR {+} &),ctrl-o:execute(open {+}),ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-a:select-all,change:top' \
                         --multi \
                         --reverse \
                         --no-mouse \
                         --height 40%\
                         --history /tmp/fzfhistory \
                         --color fg:#ebdbb2,bg:-1,hl:#fabd2f,fg+:#ebdbb2,bg+:#3c3836,hl+:#fabd2f \
                         --color info:#83a598,prompt:#bdae93,spinner:#fabd2f,pointer:#83a598,marker:#fe8019,header:#665c54"

# Use fd for FZF completion
# 1). listing files and dirs ($1 is the base path to start search) such as "vim ~/.config/**<TAB>"
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}
# 2). listing dirs such as "cd **<TAB>"
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

# Use fd for CTRL-t (paste the selected file or dir onto the command line)
export FZF_CTRL_T_COMMAND="fd $FD_DEFAULT_OPTS"

# Display the full command on the preview window (CTRL-r for command history search)
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:wrap --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)' --header 'Press CTRL-Y to copy command into clipboard'"

# CTRL-j for cd into the selected dir
bindkey '^j' fzf-cd-widget
export FZF_ALT_C_COMMAND="fd --type d $FD_DEFAULT_OPTS"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

fpath+=${0:h}/fzfutils
autoload -U ${0:h}/fzfutils/*(.:t)
