#!/usr/bin/env zsh

# Set PATH
if [[ ! "$PATH" == */Users/rockyzhang/gitrepos/fzf/bin* ]]; then
    PATH="${PATH:+${PATH}:}/Users/rockyzhang/gitrepos/fzf/bin"
fi

# Enable auto-completion and keybindings
source <(fzf --zsh)

# Default fd command
FD="fd --hidden --follow"

# Use fd instead of default find
export FZF_DEFAULT_COMMAND="$FD --type f --type l"

# Config the default options when running fzf
# Keybindings:
# - ctrl-j: down
# - ctrl-k: up
# - alt-n: down match
# - alt-p: up match
# - ctrl-n: next history
# - ctrl-p: previous history
# - ctrl-d: move cursor half page down
# - ctrl-u: move cursor halp page up
# - alt-d: move preview half page down
# - alt-u: move preview half page up
# - ctrl-a: toggle all
# - ctrl-s: toggle single selection
# - ctrl-/: change layout of the preview window
# - alt-r: toggle raw mode
# - ctrl-o: open the selections via default application
# - ctrl-y: copy the selections to system clipboard
# - ctrl-e: edit the selections via $EDITOR
# - alt-x: exclude selected items
export FZF_DEFAULT_OPTS=" \
--reverse
--height 85%
--multi
--scrollbar ┃
--info=inline
--no-separator
--history /tmp/fzfhistory
--prompt 'FZF> '
--tabstop=4
--highlight-line
--tmux 90%,85%
--bind 'ctrl-d:half-page-down,ctrl-u:half-page-up'
--bind 'alt-d:preview-half-page-down,alt-u:preview-half-page-up'
--bind 'ctrl-/:change-preview-window(down,45%|hidden|)'
--bind 'ctrl-s:toggle'
--bind 'alt-r:toggle-raw'
--bind 'alt-n:down-match,alt-p:up-match'
--bind 'ctrl-o:execute(open {+})'
--bind 'ctrl-y:execute-silent(echo -n {+} | pbcopy)'
--bind 'ctrl-e:execute($EDITOR {+} < /dev/tty > /dev/tty 2>&1)'
--bind 'alt-x:exclude-multi'
--bind 'focus:transform-preview-label:echo [ {} ]'
--preview '~/.config/fzf/fzf-previewer.sh {}'
--preview-window 'right,60%,nowrap'
"

# Use fd for FZF completion
# 1). listing files and dirs ($1 is the base path to start search) such as "vim ~/.config/**<TAB>"
_fzf_compgen_path() {
    fd --hidden --follow . "$1"
}
# 2). listing dirs such as "cd **<TAB>"
_fzf_compgen_dir() {
    fd --type d --hidden --follow . "$1"
}

# CTRL-T to paste the selected files and directories onto the command-line
# - ALT-/: toggling listing items under HOME and CWD
# - ALT-R: list items under system root
export FZF_CTRL_T_COMMAND="$FD"
export FZF_CTRL_T_OPTS="
--prompt 'Fzf [Current]> '
--header ':: ALT-/ (toggle HOME/CWD), ALT-R (Root)'
--bind 'alt-r:reload($FD . /)+change-prompt(Fzf [Root]> )'
--bind 'alt-/:transform:
    [[ ! \$FZF_PROMPT =~ HOME ]] && {
        echo \"reload($FD . $HOME)+change-prompt(Fzf [HOME]> )\";
    } || { \
        echo \"reload($FD)+change-prompt(Fzf [CWD]> )\";
    }' \
"

# CTRL-R to search the command history
export FZF_CTRL_R_OPTS=" \
    --prompt 'Command History> ' \
    --preview 'echo {}' \
    --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort' \
    --bind 'ctrl-t:track+clear-query' \
    --header ':: CTRL-Y (copy to clipboard), CTRL-T (track)' \
"

#
# CTRL-J to cd into the selected dir
#
# Define several key bindings to browser directories
#
# ALT-`: list directories under $HOME
# ALT-BS: list directories under the original $PWD
# ALT-/: list directories under the system root (/)
# ALT-H: list directories under the parent directory
# ALT-L: list directories under the selected directory
# ALT-P: list all parent directories of the current directory
#
bindkey '^j' fzf-cd-widget

# Each entry in fzf: {absolute_path}\t{relative_path}
export FZF_ALT_C_COMMAND="
$FD --type d |
while IFS= read -r rel; do
    if [[ \$PWD == / ]]; then
        printf \"/%s\t%s\n\" \"\$rel\" \"\$rel\"
    else
        printf \"%s/%s\t%s\n\" \"\$PWD\" \"\$rel\" \"\$rel\"
    fi
done
"
export FZF_ALT_C_OPTS="
--delimiter '\t'
--with-nth 2..
--accept-nth 1
--header ':: ALT-\` (HOME), ALT-BS (PWD), ALT-/ (Root)
:: ALT-H (Up), ALT-L (Into), ALT-p (Parents)'
--prompt '$PWD> '
--preview '[[ \$(command -v eza) ]] && eza -la --color=always --icons -g --group-directories-first {1} || tree -C {1} | head -200'
--bind 'alt-/:reload(
    cd -- / && $FD --type d | sed '\''s|.*|/&\\t&|'\''
)+change-prompt(/> )'
--bind 'alt-p:transform:
    base=\${FZF_PROMPT%> }
    [[ \$base == \"Parents of \"* ]] && base=\${base#Parents of }
    [[ \$base == / ]] && echo ignore && exit

    echo \"reload(
        print-parent-dirs \$base | sed '\''s/.*/&\\t&/'\''
    )+change-prompt(Parents of \$base> )\"
'
--bind 'alt-\`:reload(
    cd -- $HOME && $FD --type d | sed '\''s|.*|\\$HOME/&\\t&|'\''
)+change-prompt($HOME> )'
--bind 'alt-bs:reload(
    cd -- $PWD && $FZF_ALT_C_COMMAND
)+change-prompt($PWD> )'
--bind 'alt-h:transform:
    base=\${FZF_PROMPT%> }
    [[ \$base == / ]] && echo ignore && exit

    parent=\$(dirname -- \"\$base\")
    prefix=\${parent%/}
    prompt=\${prefix:-/}

    echo \"reload(
        cd -- \"\$parent\" && $FD --type d | sed '\''s|.*|\$prefix/&\\t&|'\''
    )+change-prompt(\$prompt> )\"
'
--bind 'alt-l:transform:
    target={1}
    target=\${target%/}
    echo \"reload(
        cd -- \"\$target\" && $FD --type d | sed '\''s|.*|\$target/&\\t&|'\''
    )+change-prompt(\$target> )\"
'
"

# fzf + git
# Reference: https://github.com/junegunn/fzf-git.sh
#
# CTRL-G F for files
# CTRL-G B for branches
# CTRL-G T for tags
# CTRL-G R for remotes
# CTRL-G H for commit hashes
# CTRL-G S for stashes
# CTRL-G L for Reflogs
# CTRL-G E for Each ref (git for-each-ref)
# CTRL-G W for Worktrees
source ~/.config/fzf/fzf-git.sh
