"$schema" = 'https://starship.rs/config-schema.json'

# Inspired by Gruvbox Rainbow preset (https://starship.rs/presets/gruvbox-rainbow)

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
$git_commit\
[](fg:color_aqua bg:color_blue)\
$all\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = 'bg:color_orange fg:color_fg0'

[os.symbols]
Windows = '󰍲 '
Ubuntu = '󰕈 '
SUSE = ' '
Raspbian = '󰐿 '
Mint = '󰣭 '
Macos = '󰀵 '
Manjaro = ' '
Linux = '󰌽 '
Gentoo = '󰣨 '
Fedora = '󰣛 '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = '󰣇 '
Artix = '󰣇 '
EndeavourOS = ' '
CentOS = ' '
Debian = '󰣚 '
Redhat = '󱄛 '
RedHatEnterprise = '󱄛 '
Pop = ' '

[username]
show_always = true
style_user = 'bg:color_orange fg:color_fg0'
style_root = 'bg:color_orange fg:color_fg0'
format = '[$user ]($style)'

[directory]
style = 'fg:color_fg0 bg:color_yellow'
format = '[ $path ]($style)'
truncation_length = 10
truncation_symbol = ' /'

[git_branch]
symbol = ' '
style = 'bg:color_aqua'
format = '[ $symbol$branch(:$remote_branch) ](fg:color_fg0 bg:color_aqua)'
truncation_symbol = ' '

[git_commit]
style = 'bg:color_aqua'
format = '[\($hash$tag\)](fg:color_fg0 bg:color_aqua)'

[git_status]
style = 'bg:color_aqua'
format = '[(\[$all_status$ahead_behind\] )](fg:color_fg0 bg:color_aqua)'

[time]
disabled = false
time_format = '%R'
style = 'bg:color_bg1'
format = '[  $time ](fg:color_fg0 bg:color_bg1)'

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[cmd_duration]
style = 'bg:color_blue'
format = '[ took $duration ](fg:color_fg0 bg:color_blue)'

[c]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[cmake]
symbol = '△ '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[conda]
style = 'bg:color_bg3'
format = '[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)'

[docker_context]
symbol = ' '
style = 'bg:color_bg3'
format = '[ $symbol( $context) ](fg:#83a598 bg:color_bg3)'

[golang]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[java]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[kotlin]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[lua]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[nodejs]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[ocaml]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[perl]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[php]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[python]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[ruby]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[rust]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'

[zig]
symbol = ' '
style = 'bg:color_blue'
format = '[ $symbol( $version) ](fg:color_fg0 bg:color_blue)'
