# Homebrew color from iTerm2

[colors]
foreground = '#008f11'
background = '#000000'
cursor_fg = '#ff261d'
cursor_bg = '#07f91d'
ansi = [
    '#1f1f1f',
    '#ab1500',
    '#00b000',
    '#a9a600',
    '#0223bf',
    '#c12dbf',
    '#00b3bf',
    '#cacaca',
]
brights = [
    '#797979',
    '#ec2100',
    '#00db00',
    '#eae600',
    '#0432ff',
    '#ec3aea',
    '#00e8ea',
    '#eaeaea',
]
selection_fg = 'none'
selection_bg = '#004703'

[metadata]
aliases = []
author = 'rockyzhang24'
name = 'matrix'
