# The classic Monokai color theme.
# Its offcial background color is #282923 but I'm now using a darker one #191a16. Monokai has only
# 6 basic colors. I ask ChatGPT to give me the corresponding bright ones.

[colors]
foreground = '#f8f8f2'
background = '#191a16'
cursor_bg = '#e3e3dc'
cursor_fg = '#000000'
ansi = [
    '#191a16',
    '#f92472',
    '#a6e22c',
    '#e7db74',
    '#67d8ef',
    '#ac80ff',
    '#fd9621',
    '#d8d8d8',
]
brights = [
    '#35362f',
    '#ff5c8a',
    '#b7f65c',
    '#fff9a3',
    '#7eefff',
    '#c8a0ff',
    '#ffb45c',
    '#f5f5f5',
]
selection_fg = 'none'
selection_bg = '#555449'

[metadata]
aliases = []
author = 'rockyzhang24'
name = 'monokai'
